### ISSUE TITLE
Can't find index.html file

### ISSUE THREAD

**Issue by ghobrialm** [kiddrew/moai-metroid#1]
Hi Kiddrew, I downloaded your zip file of Metroid but I cannot find the index.html file. All there is are the resource and src folder, along with all its subfolders. Shouldn't the index.html file be in the root folder, along with those 2 folders?

**Comment by kiddrew** [comment]
It's not a web app.  It runs using Moai.

http://getmoai.com/

It's also broken as of the newest release of Moai, and I haven't dug in to figure out why.  If it doesn't work, try installing a version of Moai from late 2013, which is when I wrote the code.

**Comment by ghobrialm** [comment]
Thank you so much for the reply! I really appreciate it 

Date: Sat, 16 Jan 2016 11:00:17 -0800
